version: '3'

services:
  opengate:
    container_name: OpenGate
    image: local/opengate
    build:
      context: ./src/
      dockerfile: ../docker/opengate/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 80:80
      - 443:443
  openldap:
    container_name: OpenLDAP
    image: osixia/openldap:1.5.0
    build:
      context: ./docker/ldap-db
      dockerfile: Dockerfile
    environment:
      LDAP_DOMAIN: opengate.io
      LDAP_ORGANIZATION: OpenGate
      LDAP_BASE_DN: dc=opengate,dc=io
      LDAP_ADMIN_PASSWORD: admin
    ports:
      - 389:389
      - 636:636
