version: '3.4'

services:
  opengate:
    container_name: am.opengate.io
    image: local/opengate
    build:
      context: .
      dockerfile: src/OpenGate/Dockerfile
  openldap:
    container_name: ldap.opengate.io
    image: osixia/openldap:1.5.0
    build:
      context: ./docker/ldap-db
      dockerfile: Dockerfile
    environment:
      LDAP_DOMAIN: opengate.io
      LDAP_ORGANIZATION: OpenGate
      LDAP_BASE_DN: dc=opengate,dc=io
      LDAP_ADMIN_PASSWORD: admin
    ports:
      - 389:389
      - 636:636
